Console.WriteLine("Enter the Dividend: ");
int dividend = int.Parse(Console.ReadLine());
Console.WriteLine("Enter the Divisor");
int divisor = int.Parse(Console.ReadLine());
int remainder;
float quotient;
quotient = dividend / divisor;
remainder = dividend % divisor;
Console.WriteLine("Remainder: "+remainder);
Console.WriteLine("Quotient: "+quotient);